sudo: required
language: python
matrix:
    include:
        - python: 3.5
        - python: 2.7

install:
  # Install test only dependency
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install backports.tempfile;
    fi
  - python setup.py install
  - pip install flake8 coveralls pytest-cov

# command to run tests
script:
  - flake8
  - py.test --cov image_dataset_viz --cov-report term-missing


after_success:
  - coveralls


# PyPI Deployment: https://docs.travis-ci.com/user/deployment/pypi/
deploy:
  provider: pypi
  user: vfdev-5
  # If password contains non alphanumeric characters
  # https://github.com/travis-ci/dpl/issues/377
  # pass it as secured variable
  password: $PYPI_TOKEN
  # otherwise, follow "How to encrypt the password": https://docs.travis-ci.com/user/encryption-keys/
  # `travis encrypt deploy.password="password"`
  #    secure: "secured_password"

  skip_cleanup: true
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "3.5"
