sudo: required
language: python
matrix:
    include:
        - python: 3.5

install:
  - pip install numpy Pillow tqdm
  - python setup.py install
  - pip install flake8 coveralls pytest-cov

# command to run tests
script:
  - py.test --cov image_dataset_viz --cov-report term-missing
  - flake8

after_success:
  - coveralls
